export const AUDIO_MAP: Record<string, string> = {
  "Find a comfortable position. Put on headphones for the full experience.": "/audio/trance/trance-entry-01.mp3",
  "Follow the dot with your eyes... keep your head still... just your eyes... gently... back and forth... that's right...": "/audio/trance/trance-fixation-01.mp3",
  "Notice the sounds that rise and fall... let them guide your breathing... breathing in as they rise... breathing out as they fall...": "/audio/trance/trance-fixation-02.mp3",
  "You might notice your breathing finding its own perfect rhythm now... effortless... automatic... and with each breath... you may find yourself becoming more comfortable...": "/audio/trance/trance-fixation-03.mp3",
  "Perhaps you can notice... your eyelids becoming pleasantly heavy... and that feels good... a welcome heaviness... that tells you everything is exactly as it should be...": "/audio/trance/trance-fixation-04.mp3",
  "Some people begin to notice a comfort spreading through them... all by itself... and you may find it happening to you now... and you can enjoy how easy it is... to simply allow this...": "/audio/trance/trance-fixation-05.mp3",
  "Perhaps you can sense a beautiful stillness... opening up inside you... and in that stillness... there might be such deep contentment... such quiet satisfaction...": "/audio/trance/trance-fixation-06.mp3",
  "You may notice each breath carrying you a little deeper... into this feeling of wellbeing... that's right... deeper now... and it can feel wonderful...": "/audio/trance/trance-fixation-07.mp3",
  "And you may realize... you are exactly where you want to be... right here... right now... and that knowing can bring such peace... such contentment...": "/audio/trance/trance-fixation-08.mp3",
  "Just the gentle movement... the soft sounds... and this growing sense of ease... everything else can simply drift away... because you are safe... and you are at peace...": "/audio/trance/trance-fixation-09.mp3",
  "Perhaps the relaxation is finding you... or perhaps you are finding it... and it's a lovely thing... that either way... this comfort can grow deeper...": "/audio/trance/trance-fixation-10.mp3",
  "And the deeper you go... the more content you might feel... and the more content you feel... the deeper you can go... such a wonderful cycle...": "/audio/trance/trance-fixation-11.mp3",
  "You might notice... a warm... pleasant glow beginning in your feet... and as you notice it... it can begin to grow...": "/audio/trance/trance-deepening-01.mp3",
  "That warmth might drift upward... bringing comfort wherever it goes... at its own perfect pace... and you can enjoy every moment of this journey...": "/audio/trance/trance-deepening-02.mp3",
  "Perhaps through your legs... a beautiful softness spreading... as if your muscles are melting into warm honey... so comfortable... so at ease...": "/audio/trance/trance-deepening-03.mp3",
  "Your body knows exactly how to do this... you can trust it completely... your deeper mind is already guiding you... into exactly the right state...": "/audio/trance/trance-deepening-04.mp3",
  "You might notice your hands feeling wonderfully comfortable... perfectly placed... and you can notice how good it feels... to simply let them rest...": "/audio/trance/trance-deepening-05.mp3",
  "Perhaps waves of comfort flowing through your arms... into your shoulders... like warm sunlight spreading through you... bringing such contentment...": "/audio/trance/trance-deepening-06.mp3",
  "You may notice your shoulders softening... releasing into comfort... and you can feel how good that release feels... allowing yourself to enjoy it fully...": "/audio/trance/trance-deepening-07.mp3",
  "Perhaps your neck is finding its perfect position of ease... and with that ease can come a beautiful feeling of freedom... and lightness...": "/audio/trance/trance-deepening-08.mp3",
  "You might notice the delicate muscles around your eyes... becoming so soft... so smooth... and your eyelids may feel wonderfully heavy... pleasantly closed...": "/audio/trance/trance-deepening-09.mp3",
  "Perhaps your whole face is beginning to radiate calm... smooth and serene... and there can be something so deeply satisfying about this... this complete peace...": "/audio/trance/trance-deepening-10.mp3",
  "You might notice a wave of pure contentment washing over you... from head to toe... every part of you... deeply... perfectly... at peace...": "/audio/trance/trance-deepening-11.mp3",
  "Now... gently press your thumb and forefinger together... and let this touch become your anchor... this feeling of deep contentment... is yours to return to... whenever you choose... simply by pressing these fingers together...": "/audio/trance/trance-deepening-12.mp3",
  "In your mind... a beautiful staircase appears... leading down into the most comfortable... most peaceful place... you have ever known...": "/audio/trance/trance-staircase-01.mp3",
  "Each step might bring twice as much comfort... twice as much peace... and with each step... you may feel that contentment doubling...": "/audio/trance/trance-staircase-02.mp3",
  "In a moment... you will see and hear some numbers... counting down from ten to one... and you may find yourself dropping more and more into relaxation... as each number takes you deeper...": "/audio/trance/trance-staircase-countdown-intro.mp3",
  "For just a moment... notice how good you already feel... notice the sounds around you... the surface supporting you... appreciate how comfortable you are...": "/audio/trance/trance-staircase-03.mp3",
  "...and now... allow yourself to go twice as deep into that comfort... that's right... so much deeper... so much more peaceful...": "/audio/trance/trance-staircase-04.mp3",
  "ten": "/audio/trance/trance-staircase-10.mp3",
  "nine": "/audio/trance/trance-staircase-09.mp3",
  "eight": "/audio/trance/trance-staircase-08.mp3",
  "seven": "/audio/trance/trance-staircase-07.mp3",
  "six": "/audio/trance/trance-staircase-06.mp3",
  "five": "/audio/trance/trance-staircase-05.mp3",
  "four": "/audio/trance/trance-staircase-count-04.mp3",
  "three": "/audio/trance/trance-staircase-count-03.mp3",
  "two": "/audio/trance/trance-staircase-count-02.mp3",
  "one": "/audio/trance/trance-staircase-count-01.mp3",
  "You are deeply at peace... and from this beautiful place of comfort... let's explore... the wonderful things your mind can do...": "/audio/trance/trance-experiments-intro.mp3",
  "In a moment... I'll count from 1 to 5... and with each number... you'll feel more alert... more present... carrying this feeling of contentment with you...": "/audio/trance/trance-emergence-intro.mp3",
  "One... a gentle brightening of awareness... feeling so good...": "/audio/trance/trance-emergence-01.mp3",
  "Two... becoming more present... carrying this deep peace with you... it stays with you...": "/audio/trance/trance-emergence-02.mp3",
  "Three... energy and vitality returning to your body... feeling wonderful... refreshed...": "/audio/meditation/meditation-emergence-03.mp3",
  "Four... almost there... take a deep, satisfying breath... feeling clear... feeling content...": "/audio/trance/trance-emergence-04.mp3",
  "Five... eyes open... wide awake... fully alert... feeling wonderful... refreshed... and deeply at peace.": "/audio/trance/trance-emergence-05.mp3",
  "Take a slow... deep breath... let your body settle...": "/audio/emdr/emdr-centering-01.mp3",
  "Feel the surface beneath you... notice the air on your skin...": "/audio/emdr/emdr-centering-02.mp3",
  "In your mind... think of a place... where you feel completely safe... and at peace...": "/audio/emdr/emdr-safeplace-01.mp3",
  "Notice the colors... the sounds... and the temperature of this place... in your mind...": "/audio/emdr/emdr-safeplace-02.mp3",
  "Choose a single word... that represents this safe place...": "/audio/emdr/emdr-safeplace-03.mp3",
  "Hold that image and word in mind...": "/audio/emdr/emdr-safeplace-04.mp3",
  "Follow the dot with your eyes... keep your head still... just your eyes... holding your safe place in mind...": "/audio/emdr/emdr-safeplace-bls.mp3",
  "Cross your arms over your upper chest, so each hand rests just below the opposite collarbone...": "/audio/emdr/emdr-butterfly-01.mp3",
  "Your fingertips should be pointing up toward your neck, resting on the area between your shoulder and collarbone...": "/audio/emdr/emdr-butterfly-02.mp3",
  "Now gently tap with your fingertips — alternating left, right, left, right — like a butterfly's wings...": "/audio/emdr/emdr-butterfly-03.mp3",
  "Keep tapping steadily on your upper chest... each tap light and rhythmic...": "/audio/emdr/emdr-butterfly-04.mp3",
  "Notice any sensations in your body as you tap... just observe them...": "/audio/emdr/emdr-butterfly-05.mp3",
  "Continue tapping for a few more moments... feeling calmer with each tap...": "/audio/emdr/emdr-butterfly-06.mp3",
  "In your mind... imagine a strong container... a box... a vault... anything that locks securely...": "/audio/emdr/emdr-container-01.mp3",
  "Place anything that's been bothering you inside... close the lid firmly...": "/audio/emdr/emdr-container-02.mp3",
  "It's held safely there... not gone... just contained for now...": "/audio/emdr/emdr-container-03.mp3",
  "Imagine the container sealing... as you follow the dot... feeling it become more and more secure... with each movement of your eyes...": "/audio/emdr/emdr-container-bls.mp3",
  "In your mind... think of a time... you felt strong... capable... or deeply at peace...": "/audio/emdr/emdr-resource-01.mp3",
  "In your mind... step into that memory... feel it... in your body...": "/audio/emdr/emdr-resource-02.mp3",
  "Where in your body do you feel that strength... or peace... let the feeling expand...": "/audio/emdr/emdr-resource-03.mp3",
  "Follow the dot... let the eye movements strengthen this feeling...": "/audio/emdr/emdr-resource-bls.mp3",
  "Scan your body from head to toe... notice how you feel now...": "/audio/emdr/emdr-bodyscan-01.mp3",
  "Observe any changes... without judgment...": "/audio/emdr/emdr-bodyscan-02.mp3",
  "Take a deep breath... you can return to your safe place... anytime you need...": "/audio/emdr/emdr-closing-01.mp3",
  "Take a deep breath... settle into this moment...": "/audio/art/art-centering-01.mp3",
  "Let your body relax... feel the ground beneath you...": "/audio/art/art-centering-02.mp3",
  "Think of something stressful... you don't need to describe it... just bring it to mind...": "/audio/art/art-scene-01.mp3",
  "See it like a scene in a movie... in your mind... notice the details...": "/audio/art/art-scene-02.mp3",
  "Hold that scene in mind... follow the dot with your eyes... keep your head still... just your eyes...": "/audio/art/art-processing-01.mp3",
  "Keep following... let whatever comes up... just be there...": "/audio/art/art-processing-02.mp3",
  "Bring the original scene back to mind... how it was... before you changed it...": "/audio/art/art-processing-return-01.mp3",
  "Follow the dot... notice what's still there...": "/audio/art/art-processing-return-02.mp3",
  "Where do you feel the tension... or discomfort... in your body... focus on that place...": "/audio/art/art-sensation-01.mp3",
  "Follow the dot... focus on where you feel it in your body... let the feeling soften...": "/audio/art/art-sensation-bls.mp3",
  "Now... in your mind... change the scene. You're in control of this image...": "/audio/art/art-vir-01.mp3",
  "Change what happens... change who's there... change how it looks or feels. Make it the way you want it to be...": "/audio/art/art-vir-02.mp3",
  "Hold the changed scene in mind... follow the dot... let it settle in...": "/audio/art/art-vir-bls.mp3",
  "Scan your body from head to toe... notice what has shifted...": "/audio/art/art-bodyscan-01.mp3",
  "Observe... without judgment...": "/audio/art/art-bodyscan-02.mp3",
  "Take a deep breath... think back to the original memory... notice how different it feels now...": "/audio/art/art-closing-01.mp3",
  "Let your eyes follow the dot moving across the screen... keep your head still... just your eyes...": "/audio/meditation/meditation-centering-01.mp3",
  "As the sounds rise... breathe in... as they hold... hold... as they fall... breathe out slowly...": "/audio/meditation/meditation-centering-02.mp3",
  "That's it... synchronize your breathing with the rhythm you hear... and allow it to become automatic... keeping your eyes on the dot...": "/audio/meditation/meditation-centering-03.mp3",
  "And perhaps you can feel that contentment now... growing with every breath... deeper... and more satisfying...": "/audio/meditation/meditation-sustain-01.mp3",
  "Some people notice the sounds welcoming them deeper... the gentle tones cradling them... and you might find you belong here... in this comfort...": "/audio/meditation/meditation-sustain-02.mp3",
  "I wonder if you can go even deeper than this... and I think you can... because you already have... and it can feel so good...": "/audio/meditation/meditation-sustain-03.mp3",
  "You might notice your mind becoming beautifully still... your body perfectly at ease... and perhaps there is such deep peace... in this moment...": "/audio/meditation/meditation-sustain-04.mp3",
  "Some people find that while their body rests here... comfortable and safe... their mind begins to float freely... drifting... weightless... free...": "/audio/meditation/meditation-sustain-05.mp3",
  "Notice how good this feels... this gift you are giving yourself... this time... this care... this peace...": "/audio/meditation/meditation-sustain-06.mp3",
  "And you may find you can go even deeper still... deeper than you thought possible... and each new depth might bring even more contentment... even more joy...": "/audio/meditation/meditation-sustain-07.mp3",
  "Perhaps you can notice a profound sense of wellbeing... spreading through every part of you... deeply... completely... perfectly at peace...": "/audio/meditation/meditation-sustain-08.mp3",
  "Some people find their body resting here... warm and safe... while their mind drifts somewhere beautiful... somewhere peaceful... somewhere that is entirely theirs...": "/audio/meditation/meditation-sustain-09.mp3",
  "And perhaps you can notice... a quiet joy... underneath all of this... a gentle smile that might come from deep within...": "/audio/meditation/meditation-sustain-10.mp3",
  "And you might notice it becoming so easy now... so effortless... your deeper mind knows exactly what to do... and you can simply enjoy...": "/audio/meditation/meditation-sustain-11.mp3",
  "I wonder how deep you can go... perhaps there is no limit... your mind vast and open... and every moment here... might bring more comfort... more peace... more contentment...": "/audio/meditation/meditation-sustain-12.mp3",
  "And you may realize that everything is exactly as it should be... and you are exactly where you want to be... you might find you belong here... in this warmth...": "/audio/meditation/meditation-sustain-13.mp3",
  "Perhaps the boundary between you and this peace... is beginning to dissolve... and you might find yourself becoming the calm itself... the stillness itself...": "/audio/meditation/meditation-sustain-14.mp3",
  "You can rest here... in this beautiful place... knowing that you are safe... you are whole... and this joy... this contentment... is always available to you...": "/audio/meditation/meditation-sustain-15.mp3",
  "Perhaps you can notice everything flowing... your breath... the sounds... this feeling of deep contentment... all moving together... perfectly...": "/audio/meditation/meditation-sustain-16.mp3",
  "Gently press your thumb and forefinger together... feel this deep contentment lock into place... this feeling is yours... whenever you press these fingers together... this peace returns...": "/audio/meditation/meditation-anchor-01.mp3",
  "Press your thumb and forefinger together again now... notice how much deeper this feeling has become... your anchor grows stronger each time... this profound peace... this contentment... stored in this simple touch...": "/audio/meditation/meditation-anchor-02.mp3",
  "One last time... press your thumb and forefinger together... at this deepest point... seal this feeling in... this is the deepest peace you have felt... and it is always here for you... always available... with this simple touch...": "/audio/meditation/meditation-anchor-03.mp3",
  "When you're ready... you'll begin to return... carrying this beautiful feeling of peace with you... it stays with you...": "/audio/meditation/meditation-emergence-intro.mp3",
  "One... a gentle brightening... feeling so content... so grateful for this time...": "/audio/meditation/meditation-emergence-01.mp3",
  "Two... becoming more present now... and this deep peace... it travels with you...": "/audio/meditation/meditation-emergence-02.mp3",
  "Four... almost there... take a deep... satisfying breath... feeling clear... feeling content...": "/audio/meditation/meditation-emergence-04.mp3",
  "Five... eyes open... fully present... feeling wonderful... carrying this deep sense of peace... and contentment... with you.": "/audio/meditation/meditation-emergence-05.mp3",
  "Let's pause and ground yourself. This is a simple exercise to bring you back to the present moment.": "/audio/grounding/grounding-intro.mp3",
  "Look around and name 5 things you can see...": "/audio/grounding/grounding-01-see.mp3",
  "Notice 4 things you can physically feel...": "/audio/grounding/grounding-02-touch.mp3",
  "Listen for 3 sounds around you...": "/audio/grounding/grounding-03-hear.mp3",
  "Identify 2 things you can smell...": "/audio/grounding/grounding-04-smell.mp3",
  "Notice 1 thing you can taste...": "/audio/grounding/grounding-05-taste.mp3",
  "Good. Take a deep breath. You're here, you're safe.": "/audio/grounding/grounding-closing.mp3",
  "Rest your hands on your lap or desk...": "/audio/experiments/experiment-arm-01.mp3",
  "Focus on your dominant hand...": "/audio/experiments/experiment-arm-02.mp3",
  "Imagine a helium balloon tied gently to your wrist... feel the upward pull...": "/audio/experiments/experiment-arm-03.mp3",
  "You don't need to lift your hand. Just notice if it wants to rise...": "/audio/experiments/experiment-arm-04.mp3",
  "Focus on your left hand. Notice the temperature of the air on your skin...": "/audio/experiments/experiment-sensory-01.mp3",
  "Now imagine holding a warm cup of tea...": "/audio/experiments/experiment-sensory-02.mp3",
  "Feel the heat radiating into your palm... the ceramic smooth and warm...": "/audio/experiments/experiment-sensory-03.mp3",
  "The warmth spreading through your fingers...": "/audio/experiments/experiment-sensory-04.mp3",
  "If you have a necklace, keychain, or anything on a string — hold it still in front of you.": "/audio/experiments/experiment-pendulum-01.mp3",
  "Without moving your hand, simply think about the pendulum swinging left to right...": "/audio/experiments/experiment-pendulum-02.mp3",
  "Just think the thought. Watch what happens...": "/audio/experiments/experiment-pendulum-03.mp3",
  "Close your eyes for what feels like one minute. Open them when you think a minute has passed.": "/audio/experiments/experiment-time-intro.mp3",
  "Interesting, isn't it? In trance, time becomes more flexible...": "/audio/experiments/experiment-time-result.mp3",
  "breathe in": "/audio/breath/breath-in.mp3",
  "hold": "/audio/breath/breath-hold.mp3",
  "breathe out": "/audio/breath/breath-out.mp3"
};
